artifacts_directory: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion/
  raw_data_path: artifacts/data_ingestion/raw_data.csv
  train_data_path: artifacts/data_ingestion/train_data.csv
  test_data_path: artifacts/data_ingestion/test_data.csv

data_transformation:
  root_dir: artifacts/data_transformation/
  preprocessor_obj_path: artifacts/data_transformation/preprocessor.joblib
  train_arr_path: artifacts/data_transformation/train_arr.csv
  test_arr_path: artifacts/data_transformation/test_arr.csv

model_training:
  model_path: artifacts/model_training/model.pkl
  model_metrics_path: artifacts/model_training/model_metrics.json

model_evaluation:
  model_metrics_path: artifacts/model_evaluation/model_metrics.json

